---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.4
    app.quarkus.io/build-timestamp: 2025-05-09 - 12:33:23 +0000
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: workflow
  namespace: simple-conditional
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: workflow
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: workflow-view
  namespace: simple-conditional
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: workflow
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.4
    app.quarkus.io/build-timestamp: 2025-05-08 - 17:03:09 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: workflow
  name: workflow
  namespace: simple-conditional
spec:
  template:
    spec:
      serviceAccountName: workflow
      containers:
        - image: ghcr.io/atnog/poliflow-test-applications/simple-conditional/workflow
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: workflow
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: null
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
