---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: photo-database-new-trigger-workflow
  namespace: valve
spec:
  broker: broker
  filters:
    - any:
        - exact:
            type: photo.database.new
        - exact:
            type: info.database.new
        - exact:
            type: info.database.result
        - exact:
            type: info.database.resultClient
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: http-request-received-trigger-workflow
  namespace: valve
spec:
  broker: broker
  filter:
    attributes:
      type: http.request.received
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: workflow
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: sb-workflow
  namespace: valve
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: broker
      namespace: valve
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: broker
  namespace: valve
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
