---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: http-request-received-trigger-workflow
  namespace: simple-parallel
spec:
  broker: broker
  filter:
    attributes:
      type: http.request.received
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: workflow
---
apiVersion: eventing.knative.dev/v1
kind: Broker
metadata:
  annotations:
    eventing.knative.dev/broker.class: Kafka
  name: broker
  namespace: simple-parallel
spec:
  config:
    apiVersion: v1
    kind: ConfigMap
    name: kafka-broker-config
    namespace: knative-eventing
