---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.4
    app.quarkus.io/commit-id: 5381217edafaa3e6016ac5411ae8ab203fe98662
    app.quarkus.io/vcs-uri: https://github.com/<organization>/knative-argo-workflows-apps-kit.git
    app.quarkus.io/build-timestamp: 2025-05-14 - 13:25:57 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: workflow
  name: workflow
  namespace: bank-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-view
  namespace: bank-app
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
  - kind: ServiceAccount
    name: workflow
    namespace: bank-app
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/quarkus-version: 3.8.4
    app.quarkus.io/commit-id: 5381217edafaa3e6016ac5411ae8ab203fe98662
    app.quarkus.io/vcs-uri: https://github.com/<organization>/knative-argo-workflows-apps-kit.git
    app.quarkus.io/build-timestamp: 2025-05-14 - 13:25:57 +0000
  labels:
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: workflow
  name: workflow
  namespace: bank-app
spec:
  template:
    spec:
      serviceAccountName: workflow
      containers:
        - image: ghcr.io/<organization>/poliflow-test-applications/bank-app/workflow:latest
          imagePullPolicy: Always
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /q/health/live
          #     port: null
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
          name: workflow
          ports:
            - containerPort: 8080
              name: http1
              protocol: TCP
          # readinessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /q/health/ready
          #     port: null
          #     scheme: HTTP
          #   initialDelaySeconds: 5
          #   periodSeconds: 10
          #   successThreshold: 1
          #   timeoutSeconds: 10
